### ISSUE TITLE
Refactor or add id parameter for /menuData endpoint

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/campus-density-backend#46]
Currently, the `menuData` endpoint has the following parameters:

- facility
- startDate
- endDate
- q (not sure if implemented)

The `facility` parameter should be refactored to `id` to be consistent with all our other endpoints. Or, we should add `id` as a param to ensure backwards compatibility.

**Comment by kungpaogao** [comment]
similarly, although less important imo, we should probably rename `description` to `meal` in the response

**Comment by AnshG714** [comment]
Yes chief

Right now, I added an ID query param for the menuData route, but it still uses facility as a fallback bc the frontend hasn't migrated yet. I'll coordinate with iOS/Android to use meal instead of description later, stuff might start breaking if I change it and deploy now. Alternatively I can always duplicate a field in the response JSON (so both `description` and `meal` would b e sent back and have the same data), but I don't know if this is necessary??

**Comment by kungpaogao** [comment]
yah, idk if necessary. Thank you for the PR though!!
